# Generated by Django 5.2.17 on 2026-09-09 01:09

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models

import explorer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("dataset_id", models.TextField(null=True)),
                ("url", models.TextField(null=True)),
                ("title", models.TextField(null=True)),
                ("author", models.TextField(null=True)),
                ("publish_date", models.DateTimeField(null=True)),
                ("content", models.TextField(null=True)),
                ("text", models.TextField(null=True)),
                ("text_excerpt", models.TextField(null=True)),
                ("enrichment_attempts", models.IntegerField(null=True)),
                ("metadata", explorer.models.DecodedJSONField(null=True)),
                ("raw_gcs_path", models.TextField(null=True)),
                ("status", models.TextField()),
                ("wire_check_status", models.TextField()),
                (
                    "text_length",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Length(
                            django.db.models.functions.comparison.Coalesce(
                                "content",
                                "text",
                                "text_excerpt",
                                models.Value(""),
                                output_field=models.TextField(),
                            )
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                ("wire", explorer.models.DecodedJSONField(null=True)),
                ("created_at", models.DateTimeField()),
                ("primary_label", models.TextField(null=True)),
                ("primary_label_confidence", models.FloatField(null=True)),
                ("alternate_label", models.TextField(null=True)),
                ("alternate_label_confidence", models.FloatField(null=True)),
            ],
            options={
                "db_table": "articles",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleGeoid",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("geoid", models.TextField()),
                ("geoid_level", models.TextField()),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.TextField(null=True)),
            ],
            options={
                "db_table": "article_geoids",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleOrganization",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("org_type", models.TextField(null=True)),
                ("boundary", models.TextField(null=True)),
                ("role_in_story", models.TextField(null=True)),
                ("nature", models.TextField(null=True)),
                ("mention_count", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "article_organizations",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArticlePerson",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("sort_key", models.TextField(null=True)),
                ("title", models.TextField(null=True)),
                ("affiliation", models.TextField(null=True)),
                ("person_type", models.TextField(null=True)),
                ("role_in_story", models.TextField(null=True)),
                ("nature", models.TextField(null=True)),
                ("public_figure", models.BooleanField(null=True)),
                ("mention_count", models.IntegerField(null=True)),
                ("quotes", explorer.models.DecodedJSONField(null=True)),
            ],
            options={
                "db_table": "article_people",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArticlePlace",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.TextField(null=True)),
                ("place_type", models.TextField(null=True)),
                ("city", models.TextField(null=True)),
                ("county", models.TextField(null=True)),
                ("state", models.TextField(null=True)),
                ("address", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("mention_text", models.TextField(null=True)),
                ("is_point", models.BooleanField(null=True)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("geocoder", models.TextField(null=True)),
                ("geoid", models.TextField(null=True)),
                ("geoid_level", models.TextField(null=True)),
            ],
            options={
                "db_table": "article_places",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateLink",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("source_name_raw", models.TextField(db_column="source", null=True)),
                ("dataset_id", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("error_message", models.TextField(null=True)),
                ("discovered_at", models.DateTimeField(null=True)),
                ("discovered_by", models.TextField(null=True)),
                ("meta", explorer.models.DecodedJSONField(null=True)),
            ],
            options={
                "db_table": "candidate_links",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ContentTypeDetection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("detected_type", models.TextField(null=True)),
                ("detection_method", models.TextField(null=True)),
                ("confidence_score", models.FloatField(null=True)),
                ("reason", models.TextField(null=True)),
                ("evidence", models.TextField(null=True)),
            ],
            options={
                "db_table": "content_type_detection_telemetry",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(unique=True)),
                ("label", models.TextField(unique=True)),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "meta",
                    explorer.models.DecodedJSONField(db_column="metadata", null=True),
                ),
                ("owner_name", models.TextField(blank=True, null=True)),
                ("owner_email", models.TextField(blank=True, null=True)),
                ("cron_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "datasets",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetSource",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "dataset_sources",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExtractionTelemetry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operation_id", models.TextField(null=True)),
                ("url", models.TextField(null=True)),
                ("publisher", models.TextField(null=True)),
                ("host", models.TextField(null=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("total_duration_ms", models.IntegerField(null=True)),
                ("http_status_code", models.IntegerField(null=True)),
                ("content_length", models.IntegerField(null=True)),
                ("is_success", models.BooleanField(null=True)),
                ("error_message", models.TextField(null=True)),
                ("error_type", models.TextField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("dataset_id", models.TextField(null=True)),
                ("candidate_link_id", models.TextField(null=True)),
            ],
            options={
                "db_table": "extraction_telemetry_v2",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Gazetteer",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("dataset_id", models.TextField(null=True)),
                ("source_id", models.TextField(null=True)),
                ("category", models.TextField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "gazetteer",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("job_type", models.TextField()),
                ("job_name", models.TextField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("exit_status", models.TextField(null=True)),
                ("dataset_id", models.TextField(null=True)),
                ("records_processed", models.IntegerField(null=True)),
                ("records_created", models.IntegerField(null=True)),
                ("records_updated", models.IntegerField(null=True)),
                ("errors_count", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "jobs",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("host", models.TextField()),
                ("host_norm", models.TextField(unique=True)),
                ("canonical_name", models.TextField(null=True)),
                ("city", models.TextField(null=True)),
                ("county", models.TextField(null=True)),
                ("owner", models.TextField(null=True)),
                ("type", models.TextField(null=True)),
                ("status", models.TextField(default="active", null=True)),
                (
                    "meta",
                    explorer.models.DecodedJSONField(db_column="metadata", null=True),
                ),
                ("rss_consecutive_failures", models.IntegerField(default=0)),
                (
                    "rss_transient_failures",
                    explorer.models.DecodedJSONField(default=list),
                ),
                ("has_paywall", models.BooleanField(default=False)),
                ("requires_login", models.BooleanField(default=False)),
                ("auth_type", models.TextField(blank=True, null=True)),
                ("auth_secret_name", models.TextField(blank=True, null=True)),
                (
                    "auth_config",
                    explorer.models.DecodedJSONField(blank=True, null=True),
                ),
                (
                    "subscription_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("subscription_period", models.TextField(blank=True, null=True)),
                ("login_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sources",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UrlVerification",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("storysniffer_result", models.BooleanField(null=True)),
                ("verification_confidence", models.FloatField(null=True)),
                ("verified_at", models.DateTimeField(null=True)),
                ("previous_status", models.TextField(null=True)),
                ("new_status", models.TextField(null=True)),
                ("article_headline", models.TextField(null=True)),
                ("article_excerpt", models.TextField(null=True)),
                ("dataset_id", models.TextField(null=True)),
            ],
            options={
                "db_table": "url_verifications",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlockedInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("rows", models.JSONField(default=list)),
                ("took_ms", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "blocked inventories",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleEnrichment",
            fields=[
                (
                    "article",
                    models.OneToOneField(
                        db_column="article_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="enrichment",
                        serialize=False,
                        to="explorer.article",
                    ),
                ),
                ("profile_version", models.IntegerField(null=True)),
                ("skip_reason", models.TextField(null=True)),
                ("model", models.TextField(null=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                ("enriched_at", models.DateTimeField(null=True)),
                ("is_news_content", models.BooleanField(null=True)),
                ("content_gate_reason", models.TextField(null=True)),
                ("scope", models.TextField(null=True)),
                ("scope_confidence", models.FloatField(null=True)),
                ("subject", models.TextField(null=True)),
                ("subject_confidence", models.FloatField(null=True)),
                ("topic", models.TextField(null=True)),
                ("topic_confidence", models.FloatField(null=True)),
                ("format", models.TextField(null=True)),
                ("format_confidence", models.FloatField(null=True)),
                ("timeframe", models.TextField(null=True)),
                ("timeframe_confidence", models.FloatField(null=True)),
                ("user_need", models.TextField(null=True)),
                ("user_need_confidence", models.FloatField(null=True)),
                ("rationales", explorer.models.DecodedJSONField(null=True)),
                ("point_place", models.TextField(null=True)),
                ("point_method", models.TextField(null=True)),
                ("point_geoid", models.TextField(null=True)),
                ("point_geoid_level", models.TextField(null=True)),
                ("point_lat", models.FloatField(null=True)),
                ("point_lon", models.FloatField(null=True)),
                ("point_zcta", models.TextField(null=True)),
                ("geoids", models.TextField(null=True)),
                ("geo_skip_reason", models.TextField(null=True)),
            ],
            options={
                "db_table": "article_enrichment",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
