# Generated by Django 5.2.17 on 2026-09-11 19:09

"""`ArticlePlaceManual` in migration state, and no table.

The model is `managed = False`: the crawler owns
`article_places_manual` and creates it in its own alembic revision. Django
still records unmanaged models in migration state, and
`makemigrations --check` fails the build until it does -- which is what
caught this rather than it reaching CI.

Nothing here runs against the database.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePlaceManual",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.TextField(null=True)),
                ("city", models.TextField(null=True)),
                ("county", models.TextField(null=True)),
                ("state", models.TextField(null=True)),
                ("geoid", models.TextField(null=True)),
                ("geoid_level", models.TextField(null=True)),
                ("is_point", models.BooleanField(default=False)),
                ("added_by", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(null=True)),
            ],
            options={
                "db_table": "article_places_manual",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
