# Generated by Django 5.2.17 on 2026-08-21 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import visuals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("bigquery", "BigQuery query"),
                            ("gcs", "bucket object"),
                        ],
                        max_length=20,
                    ),
                ),
                ("query", models.TextField(blank=True, default="")),
                (
                    "bucket_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "template",
                    models.CharField(
                        max_length=100, validators=[visuals.models._validate_renderer]
                    ),
                ),
                (
                    "allow_live",
                    models.BooleanField(
                        default=False,
                        help_text="Permit ?live=1 on the feed — the embed default stays pinned.",
                    ),
                ),
                (
                    "frame_ancestors",
                    models.CharField(
                        default="'self'",
                        help_text="CSP frame-ancestors sources, space-separated.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="VisualSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="visuals.visual",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="visual",
            name="pinned_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="visuals.visualsnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="visualsnapshot",
            constraint=models.UniqueConstraint(
                fields=("visual", "version"), name="uq_visual_version"
            ),
        ),
    ]
