# Generated by Django 5.2.17 on 2026-08-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visual",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="visual",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("bigquery", "BigQuery query"),
                    ("gcs", "bucket object"),
                    ("inline", "uploaded data"),
                ],
                max_length=20,
            ),
        ),
    ]
