# Generated by Django 5.2.17 on 2026-08-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0002_visual_config_alter_visual_source_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="visual",
            name="spec",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="visual",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("bigquery", "BigQuery query"),
                    ("gcs", "bucket object"),
                    ("inline", "uploaded data"),
                    ("corpus", "the research corpus"),
                ],
                max_length=20,
            ),
        ),
    ]
