# Generated by Django 5.2.17 on 2026-09-03 23:56

from django.db import migrations

import visuals.models


class Migration(migrations.Migration):
    """jsonb reorders a document's keys; a snapshot's column order is the
    author's and has to survive. jsonb -> json casts in place.

    Snapshots taken before this keep the order jsonb left them in -- the
    original is gone, not recoverable -- so an already-published visual's
    CSV header does not change. New snapshots carry the uploaded order.
    """

    dependencies = [
        ("visuals", "0007_folders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualsnapshot",
            name="data",
            field=visuals.models.OrderedJSONField(),
        ),
    ]
