# Generated by Django 5.2.17 on 2026-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0008_snapshot_data_is_json_not_jsonb"),
    ]

    operations = [
        migrations.AddField(
            model_name="visual",
            name="keep_updated",
            field=models.BooleanField(
                default=False,
                help_text="Let the daily refresh publish new data, when it differs from what is pinned. Off means the pin moves only when you publish.",
            ),
        ),
    ]
