# Generated by Django 5.2.17 on 2026-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0009_a_visual_can_keep_itself_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
