# Generated by Django 5.2.17 on 2026-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0010_folder_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "outlet_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=36)),
                ("name", models.CharField(max_length=300)),
                ("state", models.CharField(default="MO", max_length=2)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("county", models.CharField(blank=True, default="", max_length=120)),
                (
                    "county_fips",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=5
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "location_basis",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("host", models.CharField(blank=True, default="", max_length=300)),
                ("owner", models.CharField(blank=True, default="", max_length=300)),
                ("status", models.CharField(blank=True, default="", max_length=40)),
                ("status_basis", models.TextField(blank=True, default="")),
                (
                    "merged_into",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("aka", models.TextField(blank=True, default="")),
                ("on_map", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, default="", max_length=40)),
                ("march_articles", models.PositiveIntegerField(default=0)),
                ("row", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outlet_registry",
                "ordering": ["state", "county", "name"],
            },
        ),
    ]
