# Generated by Django 5.2.17 on 2026-09-27 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0011_outlet_registry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outlet_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=36
                    ),
                ),
                ("outlet_name", models.CharField(max_length=300)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("sold", "Sold"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                            ("launched", "Launched"),
                            ("relaunched", "Relaunched"),
                            ("renamed", "Renamed"),
                            ("owner_changed", "Owner changed"),
                            ("correction", "Correction"),
                            ("retraction", "Retraction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "on this day"),
                            ("month", "in this month"),
                            ("year", "in this year"),
                            ("by", "on or before"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "from_owner",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("to_owner", models.CharField(blank=True, default="", max_length=300)),
                (
                    "merged_into",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("new_name", models.CharField(blank=True, default="", max_length=300)),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("sets_current", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("origin", models.CharField(blank=True, default="", max_length=40)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retracts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retracted_by",
                        to="visuals.outletevent",
                    ),
                ),
            ],
            options={
                "db_table": "outlet_event",
                "ordering": ["effective_date", "recorded_at", "id"],
            },
        ),
    ]
