# Generated by Django 5.2.17 on 2026-09-27 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0012_outlet_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("bigquery", "BigQuery query"),
                    ("gcs", "bucket object"),
                    ("inline", "uploaded data"),
                    ("corpus", "the research corpus"),
                    ("stories", "the outlet stories list"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OutletStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.DateField()),
                ("source", models.CharField(max_length=120)),
                ("headline", models.CharField(max_length=400)),
                ("url", models.URLField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Ownership or closure", "Ownership or closure"),
                            ("Historical", "Historical"),
                            ("Mention only", "Mention only"),
                        ],
                        default="Ownership or closure",
                        max_length=40,
                    ),
                ),
                ("publications", models.TextField(blank=True, default="")),
                ("owners", models.TextField(blank=True, default="")),
                ("text", models.TextField(blank=True, default="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "outlet_story",
                "ordering": ["-published", "headline"],
            },
        ),
    ]
