# Generated by Django 5.2.17 on 2026-09-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0013_outlet_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="outletevent",
            name="new_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="outletevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("sold", "Sold"),
                    ("merged", "Merged"),
                    ("closed", "Closed"),
                    ("launched", "Launched"),
                    ("relaunched", "Relaunched"),
                    ("renamed", "Renamed"),
                    ("owner_changed", "Owner changed"),
                    ("correction", "Correction"),
                    ("status", "Status reviewed"),
                    ("retraction", "Retraction"),
                ],
                max_length=20,
            ),
        ),
    ]
