# Generated by Django 5.2.17 on 2026-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0014_outlet_event_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CensusValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("level", models.CharField(max_length=10)),
                ("geoid", models.CharField(max_length=11)),
                ("variable", models.CharField(max_length=60)),
                ("estimate", models.FloatField(blank=True, null=True)),
                ("moe", models.FloatField(blank=True, null=True)),
                ("percent", models.FloatField(blank=True, null=True)),
                ("percent_moe", models.FloatField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "census_layer_value",
                "indexes": [
                    models.Index(
                        fields=["year", "level", "variable"],
                        name="census_laye_year_52ad1e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "level", "geoid", "variable"),
                        name="census_value_one_per_place",
                    )
                ],
            },
        ),
    ]
