# Generated by Django 5.2.17 on 2026-08-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_create_role_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("datadesk", "Datadesk"),
                            ("sources", "Source Directory"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="A dataset slug, or blank for the whole application.",
                        max_length=100,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer — read"),
                            ("reviewer", "Reviewer — read, and dispositions"),
                            ("editor", "Editor — read, dispositions, and imports"),
                            ("designer", "Designer — read, and authoring visuals"),
                            ("admin", "Admin — everything, every scope"),
                        ],
                        max_length=32,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["app", "scope", "role"],
                "indexes": [
                    models.Index(fields=["user", "app"], name="grant_user_app_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "app", "scope"),
                        name="one_role_per_user_app_scope",
                    )
                ],
            },
        ),
    ]
