# Generated by Django 5.2.17 on 2026-08-23 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_grant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "admin"), _negated=True),
                    ("scope", ""),
                    _connector="OR",
                ),
                name="admin_grants_are_application_wide",
            ),
        ),
    ]
