# Generated by Django 5.2.17 on 2026-08-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_grant_admin_grants_are_application_wide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer — reads and exports"),
                    ("reviewer", "Reviewer — corrects the data that is there"),
                    ("editor", "Editor — corrects it, and brings new data in"),
                    ("designer", "Designer — reads, and authors visuals"),
                    ("admin", "Admin — everything, every scope, plus user admin"),
                ],
                max_length=32,
            ),
        ),
    ]
