# Generated by Django 5.2.17 on 2026-08-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_retire_role_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("datadesk", "Datadesk"),
                            ("sources", "Source Directory"),
                        ],
                        default="datadesk",
                        max_length=32,
                    ),
                ),
                ("scope", models.SlugField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer — reads and exports"),
                            ("reviewer", "Reviewer — corrects the data that is there"),
                            ("editor", "Editor — corrects it, and brings new data in"),
                            ("designer", "Designer — reads, and authors visuals"),
                            (
                                "admin",
                                "Admin — everything, every scope, plus user admin",
                            ),
                        ],
                        default="designer",
                        max_length=32,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_invitation",
                "ordering": ("email",),
            },
        ),
    ]
