# Generated by Django 5.2.17 on 2026-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer — reads and exports"),
                    ("designer", "Designer — and authors visuals"),
                    ("reviewer", "Reviewer — and corrects the data that is there"),
                    ("editor", "Editor — and brings new data in"),
                    ("admin", "Admin — everything, every scope, plus user admin"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer — reads and exports"),
                    ("designer", "Designer — and authors visuals"),
                    ("reviewer", "Reviewer — and corrects the data that is there"),
                    ("editor", "Editor — and brings new data in"),
                    ("admin", "Admin — everything, every scope, plus user admin"),
                ],
                default="designer",
                max_length=32,
            ),
        ),
    ]
