# Generated by Django 5.2.17 on 2026-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="target",
            field=models.CharField(default="articles", max_length=20),
        ),
    ]
