# Generated by Django 5.2.17 on 2026-08-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_reason"),
        ("review", "0002_importbatch_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(default="", max_length=120)),
                ("target", models.CharField(default="sources", max_length=20)),
                ("record_id", models.TextField()),
                ("record_label", models.TextField(blank=True, default="")),
                ("dataset", models.CharField(blank=True, default="", max_length=100)),
                ("field", models.CharField(max_length=60)),
                ("current_value", models.TextField(blank=True, default="")),
                ("proposed_value", models.TextField(blank=True, default="")),
                (
                    "finding",
                    models.CharField(
                        choices=[
                            ("ready", "Passes every check"),
                            ("owner_conflict", "Names a different owner"),
                            ("unknown_owner", "Owner not recognised"),
                            ("gazetteer", "Not a place or county here"),
                            ("duplicate", "Source file disagrees with itself"),
                            ("no_match", "No such record"),
                        ],
                        max_length=30,
                    ),
                ),
                ("why", models.TextField(blank=True, default="")),
                ("suggestion", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("fixed", "fixed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("final_value", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="audit.auditlogentry",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="review.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["record_label", "field"],
                "indexes": [
                    models.Index(
                        fields=["state", "target"], name="review_chan_state_cf973f_idx"
                    ),
                    models.Index(
                        fields=["record_id"], name="review_chan_record__b9b14d_idx"
                    ),
                ],
            },
        ),
    ]
