# Generated by Django 5.2.17 on 2026-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_changeproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeproposal",
            name="suggested_value",
            field=models.TextField(blank=True, default=""),
        ),
    ]
