# Generated by Django 5.2.17 on 2026-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_changeproposal_suggested_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeproposal",
            name="finding",
            field=models.CharField(
                choices=[
                    ("ready", "Nothing wrong with it"),
                    ("owner_conflict", "A different owner is already recorded"),
                    ("unknown_owner", "That owner is new to us"),
                    ("gazetteer", "No such place or county"),
                    ("duplicate", "The file says two different things"),
                    ("no_match", "No publisher with that id"),
                ],
                max_length=30,
            ),
        ),
    ]
