# Generated by Django 5.2.17 on 2026-08-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_alter_changeproposal_finding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeproposal",
            name="finding",
            field=models.CharField(
                choices=[
                    ("ready", "Ready to apply"),
                    ("owner_conflict", "Different owner recorded"),
                    ("unknown_owner", "Unknown owner"),
                    ("gazetteer", "No such place or county"),
                    ("duplicate", "File disagrees with itself"),
                    ("no_match", "No publisher with that id"),
                ],
                max_length=30,
            ),
        ),
    ]
