# Generated by Django 5.2.17 on 2026-08-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_changeproposal_citation_changeproposal_proposed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeproposal",
            name="submission",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="changeproposal",
            name="record_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
