# Generated by Django 5.2.17 on 2026-09-02 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0011_paywalldismissal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.TextField(unique=True)),
                ("article_label", models.TextField(blank=True, default="")),
                ("classified_as", models.TextField()),
                ("stage", models.TextField(blank=True, default="")),
                (
                    "decision",
                    models.TextField(
                        choices=[
                            ("accept", "accept"),
                            ("reject", "reject"),
                            ("reextract", "reextract"),
                        ]
                    ),
                ),
                ("rewound_to", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
    ]
