# Generated by Django 5.2.17 on 2026-09-03 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0012_extraction_decision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractiondecision",
            name="question",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="extractiondecision",
            name="status_after",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="extractiondecision",
            name="status_before",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="extractiondecision",
            name="article_id",
            field=models.TextField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="extractiondecision",
            constraint=models.UniqueConstraint(
                fields=("article_id", "question"), name="one_decision_per_question"
            ),
        ),
    ]
