# Generated by Django 5.2.17 on 2026-09-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0013_decision_per_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorklistCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_slug", models.TextField()),
                ("queue", models.TextField()),
                ("count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["dataset_slug", "queue"],
                "indexes": [
                    models.Index(
                        fields=["dataset_slug"], name="review_work_dataset_3319b1_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_slug", "queue"),
                        name="one_count_per_queue_per_dataset",
                    )
                ],
            },
        ),
    ]
