# Generated by Django 5.2.17 on 2026-09-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_the_decisions_across(apps, schema_editor):
    """Every ExtractionDecision becomes a ReviewDecision.

    The old table is left in place. Dropping it in the same migration
    that creates the new one leaves nothing to compare against if the
    move is wrong, and the rows are few enough that keeping them costs
    nothing until the read paths have run on the new record.
    """
    Extraction = apps.get_model("review", "ExtractionDecision")
    Review = apps.get_model("review", "ReviewDecision")
    carried = [
        Review(
            queue="extraction",
            subject_type="article",
            subject_id=old.article_id,
            field="",
            subject_label=old.article_label,
            claim=old.classified_as,
            stage=old.stage,
            question=old.question,
            verb=old.decision,
            value="",
            before=old.status_before,
            after=old.status_after,
            # What the verb did, in the extraction queue's own words.
            wrote={"rewound_to": old.rewound_to} if old.rewound_to else {},
            reason=old.reason,
            decided_by_id=old.decided_by_id,
        )
        for old in Extraction.objects.all().iterator()
    ]
    Review.objects.bulk_create(carried, batch_size=500)


def put_them_back(apps, schema_editor):
    """The new rows go; the old table was never emptied."""
    apps.get_model("review", "ReviewDecision").objects.filter(
        queue="extraction"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0014_worklist_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue", models.CharField(db_index=True, max_length=40)),
                ("subject_type", models.CharField(db_index=True, max_length=40)),
                ("subject_id", models.TextField(db_index=True)),
                ("field", models.CharField(blank=True, default="", max_length=60)),
                ("subject_label", models.TextField(blank=True, default="")),
                ("claim", models.TextField(blank=True, default="")),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("question", models.TextField()),
                ("verb", models.CharField(max_length=40)),
                ("value", models.TextField(blank=True, default="")),
                ("before", models.TextField(blank=True, default="")),
                ("after", models.TextField(blank=True, default="")),
                ("wrote", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
                "indexes": [
                    models.Index(
                        fields=["queue", "subject_type", "subject_id"],
                        name="review_revi_queue_c429b3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_type", "subject_id", "field", "question"),
                        name="one_review_decision_per_question",
                    )
                ],
            },
        ),
        migrations.RunPython(carry_the_decisions_across, put_them_back),
    ]
