# Generated by Django 5.2.17 on 2026-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0015_one_decision_for_every_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatedBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(db_index=True, max_length=255)),
                ("length", models.PositiveIntegerField()),
                ("articles", models.PositiveIntegerField()),
                ("sample", models.TextField(blank=True, default="")),
                ("statuses", models.JSONField(blank=True, default=dict)),
                ("latest_article", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-articles"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "length"), name="one_row_per_host_and_length"
                    )
                ],
            },
        ),
    ]
