# Generated by Django 5.2.17 on 2026-09-05 22:58

"""RepeatedBody becomes Boilerplate, keyed on the text rather than a length.

The table holds derived findings, recomputed from the crawler's corpus by
`manage.py find_boilerplate`. Dropping it loses nothing that cannot be
rebuilt in one run -- and what it holds now is the wrong findings: rows
keyed on an exact character count, which is not how boilerplate repeats.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0016_repeated_bodies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boilerplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(db_index=True, max_length=255)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, default="", max_length=32),
                ),
                ("matched_on", models.CharField(default="opening", max_length=16)),
                ("length", models.PositiveIntegerField()),
                ("length_max", models.PositiveIntegerField(default=0)),
                ("articles", models.PositiveIntegerField()),
                ("sample", models.TextField(blank=True, default="")),
                ("statuses", models.JSONField(blank=True, default=dict)),
                ("latest_article", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-articles"],
            },
        ),
        migrations.DeleteModel(
            name="RepeatedBody",
        ),
        migrations.AddConstraint(
            model_name="boilerplate",
            constraint=models.UniqueConstraint(
                fields=("host", "fingerprint"), name="one_row_per_host_and_boilerplate"
            ),
        ),
    ]
