# Generated by Django 5.2.17 on 2026-09-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0017_boilerplate_keyed_on_its_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("target_coders", models.PositiveSmallIntegerField(default=3)),
                ("stale_after_days", models.PositiveSmallIntegerField(default=14)),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(db_index=True, max_length=64)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reassigned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="review.classificationcohort",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["assigned_to", "completed_at"],
                        name="review_clas_assigne_da170d_idx",
                    ),
                    models.Index(
                        fields=["cohort", "completed_at"],
                        name="review_clas_cohort__1e0474_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "article_id", "assigned_to"),
                        name="one_assignment_per_coder_per_article",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassificationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(db_index=True, max_length=64)),
                (
                    "primary_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "secondary_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "not_local",
                                "Not local — wire or other non-local content",
                            ),
                            ("no_appropriate_category", "No appropriate category"),
                            ("too_short", "Too short to evaluate"),
                            (
                                "technical_error",
                                "Technical error — text missing or mismatched",
                            ),
                            ("paywall_stub", "Paywall stub"),
                            ("garbage_text", "Garbage text"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("stratum", models.CharField(blank=True, default="", max_length=20)),
                ("inclusion_probability", models.FloatField(default=1.0)),
                ("dataset_id", models.CharField(blank=True, default="", max_length=64)),
                ("seconds_spent", models.PositiveIntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="review.classificationcohort",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
                "indexes": [
                    models.Index(
                        fields=["cohort", "article_id"],
                        name="review_clas_cohort__bcebcf_idx",
                    ),
                    models.Index(
                        fields=["primary_label"], name="review_clas_primary_4639fd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article_id", "decided_by"),
                        name="one_classification_per_coder_per_article",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassificationSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(db_index=True, max_length=64)),
                (
                    "stratum",
                    models.CharField(
                        choices=[
                            ("confident", "confident"),
                            ("uncertain", "uncertain"),
                            ("random", "random"),
                            ("unlabelled", "unlabelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inclusion_probability", models.FloatField(default=1.0)),
                ("dataset_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "model_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("model_confidence", models.FloatField(blank=True, null=True)),
                ("drawn_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="review.classificationcohort",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cohort", "stratum"],
                        name="review_clas_cohort__125e4c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "article_id"),
                        name="one_sample_per_cohort_article",
                    )
                ],
            },
        ),
    ]
